### PR TITLE
Add fee per kB to transaction view

### PR DESCRIPTION
**Pull request by dabura667**
https://www.reddit.com/r/Bitcoin/comments/3ceyaz/block_explorers_please_display_feeperkb/

### CODE REVIEW

**Comment by matiu** [comment]
That was fast! :) Thanks a lot. 

We should update the string 'fee-per-kb' in settings to 'fee rate', do you agree?

**Comment by dabura667** [comment]
Ahh you're talking about Copay? Yes, I think fee rate is a good name for the setting, and when showing the value the text after the unit should be "xxx yyy per kB" where yyy is unit and xxx is value.

**Comment by zedlander** [comment]
this breaks on newly minted coins (no fees) with "value error per kB". Eg: https://insight.bitpay.com/tx/14f76477389a2b26e5a9404b18958ab8e57ddfbb6987a050f6c24689bcab5325

**Comment by dabura667** [comment]
https://github.com/bitpay/insight/pull/638

Thanks for the catch.

**Pull request merged**
