### PR TITLE
Replaced "/api with window.apiPrefix+"

### PR DESCRIPTION
**Pull request by oliverdowling**
Fix for different api locations, since insight-api has moved for bitcore-node.

### CODE REVIEW

**Comment by oliverdowling** [comment]
I've actually made a couple of other changes to fix my installation, will update the pull request, if you you think you are going to merge it, otherwise I'll just leave for now, since you guys are still working on it.

**Comment by braydonf** [comment]
I think we need to update these with the updates, or have a script that generates them upon installation. Did you run `grunt compile`?

**Comment by oliverdowling** [comment]
I did not run `grunt compile`, I wasn't aware I should. Unfortunately, I haven't really written much JavaScript in a number of years, and my nodejs experience is limited, so I was using this project, on a topic that interest me, to delve into it. I'll check out the grunt part of it when I next get some free time.

This is what I did to get it running:

* Install and set up `nodejs` 0.12 with `nvm`
* Install `bitcore-node@latest` (0.3.0-beta.6) globally, create a node pointing to my bitcoin data folder, start and let sync for a while
* Cloned `insight` and `insight-api` repositories and checked out the 0.3.0 branches.
* Stopped `bitcore-node`, installed "`insight-ui`" and `insight-api` from my local clones, and fixed the `bitcore-node.json` file ("services" were referencing the path to my cloned repos, and not the `npm` install.
* Started `bitcore-node`, and then made a few changes to the local `npm` packages, the main change, that was completely breaking the install was the one in this PR, but I made other changes, e.g. "`/view`" to "`view`" and "`/img`" to "`../img`" (in the CSS), and some other personal preference changes, like changing the display of the sync percent complete to a whole number (left it as is on the status page)

**Comment by braydonf** [comment]
The changes should be committed in now, thanks for sharing your process.

**Pull request closed without merging**
